.angular_cli: &ng_image
  image: node:latest

.npm_install:
  - &npm_install
    npm install --quiet


image: registry.gitlab.com/gitlab-examples/openshift-deploy

variables:
  # Application deployment domain
  KUBE_DOMAIN: starter-us-east-1.openshiftapps.com

stages:
  - linter
  - test
  - build
  - review
  - staging
  - e2e
  - production
  - cleanup

cache:
  untracked: true
  key: "$CI_COMMIT_REF_NAME/$CI_PIPELINE_ID"
  paths:
  - node_modules

linter:
  <<: *ng_image
  stage: linter
  script:
    - *npm_install
    - node_modules/.bin/ng lint
  only:
    - branches

test:
  <<: *ng_image
  stage: test
  script:
    - *npm_install
    - node_modules/.bin/ng test -sr
  only:
    - branches

build:
  <<: *ng_image
  stage: build
  script:
    - *npm_install
    - node_modules/.bin/ng build --prod
  artifacts:
    paths:
    - dist/
  only:
    - branches

review:
  stage: review
  variables:
    CI_ENVIRONMENT_URL: http://$CI_PROJECT_NAME-$CI_ENVIRONMENT_SLUG.$KUBE_DOMAIN
  before_script:
  - docker login -u gitlab-ci-token -p "$CI_BUILD_TOKEN" "$CI_REGISTRY"
  script:
    - docker build -t "$CI_REGISTRY_IMAGE:docker-image" .
    - docker push "$CI_REGISTRY_IMAGE:docker-image"
    - command deploy
  environment:
    name: review/$CI_COMMIT_REF_NAME
    url: http://$CI_PROJECT_NAME-$CI_ENVIRONMENT_SLUG.$KUBE_DOMAIN
    on_stop: stop_review
  dependencies:
    - build
  only:
    - branches
  except:
    - master

stop_review:
  stage: cleanup
  variables:
    GIT_STRATEGY: none
  script:
    - command remove_deploy
  environment:
    name: review/$CI_COMMIT_REF_NAME
    action: stop
  when: manual
  only:
    - branches
  except:
    - master

staging:
  stage: staging
  variables:
    CI_ENVIRONMENT_URL: http://$CI_PROJECT_NAME-staging.$KUBE_DOMAIN
  script:
    - command deploy
  environment:
    name: staging
    url: http://$CI_PROJECT_NAME-staging.$KUBE_DOMAIN
  dependencies:
    - build
  only:
    - master

production:
  stage: production
  variables:
    CI_ENVIRONMENT_URL: http://$CI_PROJECT_NAME.$KUBE_DOMAIN
  script:
    - command deploy
  environment:
    name: production
    url: http://$CI_PROJECT_NAME.$KUBE_DOMAIN
  dependencies:
    - build
  when: manual
  only:
    - master

