image: gabrielaraujof/angular-cli:latest

stages:
  - integration
  - deploy

cache:
  untracked: true
  key: "$CI_COMMIT_REF_NAME/$CI_PIPELINE_ID"
  paths:
  - node_modules

before_script:
  - npm install --quiet

linting:
  stage: integration
  script: ng lint

testing:
  stage: integration
  script:
  - ng test -sr

bundling:
  stage: integration
  script:
  - ng build --prod
  artifacts:
    paths:
    - dist/

deploy:staging:
  stage: deploy
  script:
  - ng build --prod --bh /pypicompare/
  - mkdir public && mv dist/* public/.
  artifacts:
    paths:
    - public
  environment:
    name: staging
    url: https://gabrielaraujof.gitlab.io/pypicompare/
  dependencies:
  - bundling
  only:
  - master

pages:
  stage: deploy
  script:
  - firebase deploy -m "Pipeline $CI_PIPELINE_ID, build $CI_BUILD_ID" --token=$FIREBASE_TOKEN --project pypicompare --non-interactive
  environment:
    name: production
    url: https://pypicompare.firebaseapp.com
  only:
  - master
  when: manual
