.angular_cli: &ng_image
  image: gabrielaraujof/angular-cli:latest

.npm_install:
  - &npm_install
    npm install --quiet


image: registry.gitlab.com/gitlab-examples/kubernetes-deploy

variables:
  # Application deployment domain
  KUBE_DOMAIN: domain.example.com

stages:
  - linter
  - test
  - build
  - review
  - staging
  - e2e
  - production
  - cleanup

cache:
  untracked: true
  key: "$CI_BUILD_REF_NAME"
  paths:
  - node_modules

linter:
  <<: *ng_image
  stage: linter
  script:
    - *npm_install
    - ng lint
  only:
    - branches

test:
  <<: *ng_image
  stage: test
  script:
    - *npm_install
    - ng test -sr
  only:
    - branches

build:
  <<: *ng_image
  stage: build
  script:
    - *npm_install
    - ng build --prod
  artifacts:
    paths:
    - dist/
  only:
    - branches

review:
  stage: review
  script:
    - command deploy
  environment:
    name: review/$CI_COMMIT_REF_NAME
    url: http://$CI_PROJECT_NAME-$CI_ENVIRONMENT_SLUG.$KUBE_DOMAIN
    on_stop: stop_review
  dependencies:
    - build
  only:
    - branches
  except:
    - master

stop_review:
  stage: cleanup
  variables:
    GIT_STRATEGY: none
  script:
    - command destroy
  environment:
    name: review/$CI_COMMIT_REF_NAME
    action: stop
  when: manual
  only:
    - branches
  except:
    - master

staging:
  stage: staging
  script:
    - command deploy
  environment:
    name: staging
    url: http://$CI_PROJECT_NAME-staging.$KUBE_DOMAIN
  dependencies:
    - build
  only:
    - master

production:
  stage: production
  script:
    - command deploy
  environment:
    name: production
    url: http://$CI_PROJECT_NAME.$KUBE_DOMAIN
  dependencies:
    - build
  when: manual
  only:
    - master

