image: nginx:latest

stages:
  - linter
  - unit test
  - build
  - deploy staging
  - e2e test
  - deploy prod

cache:
  untracked: true
  key: "$CI_BUILD_REF_NAME"
  paths:
  - node_modules

linting:
  stage: linter
  image: gabrielaraujof/angular-cli:latest
  script:
  - npm install --quiet
  - ng lint

testing:
  stage: unit test
  image: gabrielaraujof/angular-cli:latest
  script:
  - npm install --quiet
  - ng test --watch=false

bundling:
  stage: build
  image: gabrielaraujof/angular-cli:latest
  script:
  - npm install --quiet
  - ng build --prod
  artifacts:
    paths:
    - dist/

deploy:staging:
  stage: deploy staging
  script:
  - firebase deploy -m "Pipeline $CI_PIPELINE_ID, build $CI_BUILD_ID" --token=$FIREBASE_TOKEN --project pypicompare --non-interactive
  environment:
    name: staging
    url: https://pypicompare.firebaseapp.com
  dependencies:
  - bundling
  only:
  - master

e2e:
  stage: e2e test
  script:
  - ng e2e
  only:
  - master

pages:
  stage: deploy prod
  script:
  - ng build --prod --bh /pypicompare/
  - mkdir public && mv dist/* public/.
  artifacts:
    paths:
    - public
  environment:
    name: production
    url: https://gabrielaraujof.gitlab.io/pypicompare/
  only:
  - master
  when: manual
